version: "3"
services:
  app:
    image: "${DOCKER_IMAGE_APP?Variable-not-set}:${TAG:-latest}"
    env_file:
      - .env
    ports:
      - 2000:2000
    links:
      - redis
    volumes:
      - "./logs:/app/logs"
      - "./app:/app/app"

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    